Traceback (most recent call last):
  File "/home/runner/micromamba/envs/agu24workshop/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/agu24workshop/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/agu24workshop/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/agu24workshop/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/agu24workshop/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/agu24workshop/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/agu24workshop/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_jp_eqs = pygmt.datasets.load_sample_data(name="japan_quakes")
df_jp_eqs.head()

# df_your_dataset = pd.read_csv("your_dataset.csv")
------------------

----- stderr -----
gmtwhich [ERROR]: Libcurl Error: Timeout was reached
----- stderr -----
gmtwhich [ERROR]: Unable to obtain remote file @tut_quakes.ngdc
----- stderr -----
gmtwhich [ERROR]: File @tut_quakes.ngdc not found!
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m df_jp_eqs [38;5;241m=[39m [43mpygmt[49m[38;5;241;43m.[39;49m[43mdatasets[49m[38;5;241;43m.[39;49m[43mload_sample_data[49m[43m([49m[43mname[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mjapan_quakes[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      2[0m df_jp_eqs[38;5;241m.[39mhead()
[1;32m      4[0m [38;5;66;03m# df_your_dataset = pd.read_csv("your_dataset.csv")[39;00m

File [0;32m~/micromamba/envs/agu24workshop/lib/python3.12/site-packages/pygmt/datasets/samples.py:351[0m, in [0;36mload_sample_data[0;34m(name)[0m
[1;32m    349[0m [38;5;28;01mif[39;00m name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m datasets:
[1;32m    350[0m     [38;5;28;01mraise[39;00m GMTInvalidInput([38;5;124mf[39m[38;5;124m"[39m[38;5;124mInvalid dataset name [39m[38;5;124m'[39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m.[39m[38;5;124m"[39m)
[0;32m--> 351[0m [38;5;28;01mreturn[39;00m [43mdatasets[49m[43m[[49m[43mname[49m[43m][49m[38;5;241;43m.[39;49m[43mfunc[49m[43m([49m[43m)[49m

File [0;32m~/micromamba/envs/agu24workshop/lib/python3.12/site-packages/pygmt/datasets/samples.py:27[0m, in [0;36m_load_japan_quakes[0;34m()[0m
[1;32m     15[0m [38;5;28;01mdef[39;00m [38;5;21m_load_japan_quakes[39m() [38;5;241m-[39m[38;5;241m>[39m pd[38;5;241m.[39mDataFrame:
[1;32m     16[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m     17[0m [38;5;124;03m    Load a table of earthquakes around Japan.[39;00m
[1;32m     18[0m 
[0;32m   (...)[0m
[1;32m     25[0m [38;5;124;03m        "longitude", "depth_km", and "magnitude" of the earthquakes.[39;00m
[1;32m     26[0m [38;5;124;03m    """[39;00m
[0;32m---> 27[0m     fname [38;5;241m=[39m [43mwhich[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m@tut_quakes.ngdc[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mdownload[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mc[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m     28[0m     [38;5;28;01mreturn[39;00m pd[38;5;241m.[39mread_csv(
[1;32m     29[0m         fname,
[1;32m     30[0m         header[38;5;241m=[39m[38;5;241m1[39m,
[0;32m   (...)[0m
[1;32m     40[0m         ],
[1;32m     41[0m     )

File [0;32m~/micromamba/envs/agu24workshop/lib/python3.12/site-packages/pygmt/helpers/decorators.py:609[0m, in [0;36muse_alias.<locals>.alias_decorator.<locals>.new_module[0;34m(*args, **kwargs)[0m
[1;32m    603[0m     msg [38;5;241m=[39m (
[1;32m    604[0m         [38;5;124m"[39m[38;5;124mParameters [39m[38;5;124m'[39m[38;5;124mY[39m[38;5;124m'[39m[38;5;124m and [39m[38;5;124m'[39m[38;5;124myshift[39m[38;5;124m'[39m[38;5;124m are no longer supported since v0.12.0. [39m[38;5;124m"[39m
[1;32m    605[0m         [38;5;124m"[39m[38;5;124mUse Figure.shift_origin(yshift=...) instead.[39m[38;5;124m"[39m
[1;32m    606[0m     )
[1;32m    607[0m     [38;5;28;01mraise[39;00m GMTInvalidInput(msg)
[0;32m--> 609[0m [38;5;28;01mreturn[39;00m [43mmodule_func[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/micromamba/envs/agu24workshop/lib/python3.12/site-packages/pygmt/src/which.py:71[0m, in [0;36mwhich[0;34m(fname, **kwargs)[0m
[1;32m     69[0m [38;5;28;01mcase[39;00m [38;5;241m0[39m:
[1;32m     70[0m     _fname [38;5;241m=[39m [38;5;124m"[39m[38;5;124m'[39m[38;5;124m, [39m[38;5;124m'[39m[38;5;124m"[39m[38;5;241m.[39mjoin(fname) [38;5;28;01mif[39;00m is_nonstr_iter(fname) [38;5;28;01melse[39;00m fname
[0;32m---> 71[0m     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mFile(s) [39m[38;5;124m'[39m[38;5;132;01m{[39;00m_fname[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m not found.[39m[38;5;124m"[39m)
[1;32m     72[0m [38;5;28;01mcase[39;00m [38;5;241m1[39m:
[1;32m     73[0m     [38;5;28;01mreturn[39;00m paths[[38;5;241m0[39m]

[0;31mFileNotFoundError[0m: File(s) '@tut_quakes.ngdc' not found.

